# === DO_NOT_EDIT: pkg-ext site ===
site_name: path_sync
# === OK_EDIT: pkg-ext site ===

# === DO_NOT_EDIT: pkg-ext theme ===
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
# === OK_EDIT: pkg-ext theme ===

# === DO_NOT_EDIT: pkg-ext nav ===
nav:
  - Home: index.md
  - config:
    - Overview: config/index.md
    - Destination: config/destination.md
    - HeaderConfig: config/headerconfig.md
    - PRDefaults: config/prdefaults.md
    - PathMapping: config/pathmapping.md
    - SrcConfig: config/srcconfig.md
    - SyncMode: config/syncmode.md
  - copy:
    - Overview: copy/index.md
    - CopyOptions: copy/copyoptions.md
  - dep_update:
    - Overview: dep_update/index.md
    - CommitConfig: dep_update/commitconfig.md
    - DepConfig: dep_update/depconfig.md
    - OnFailStrategy: dep_update/onfailstrategy.md
    - PRConfig: dep_update/prconfig.md
    - UpdateEntry: dep_update/updateentry.md
    - VerifyConfig: dep_update/verifyconfig.md
    - VerifyStep: dep_update/verifystep.md
# === OK_EDIT: pkg-ext nav ===

# === DO_NOT_EDIT: pkg-ext extensions ===
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - attr_list
# === OK_EDIT: pkg-ext extensions ===
